apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: student-deployment 
  labels: 
    app: student 
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels:  
      app: student 
  template: 
    metadata: 
      labels: 
        app: student 
    spec: 
      containers: 
        - name: student-container
          image: 267850879086.dkr.ecr.us-west-2.amazonaws.com/student:latest
          ports: 
            - containerPort: 8080
          imagePullPolicy: Always
          
        
          resources: 
            requests: 
              cpu: "100m"
              memory: "64Mi"
            limits:    
              cpu: "200m"
              memory: "128Mi"
              
